force-app/main/default/objects/Monthly_Budget__c/Monthly_Budget__c.object-meta.xml
<CustomObject>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>BUD-{00000}</displayFormat>
        <label>Monthly Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Budget__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()), MONTH(TODAY()), 1)</defaultValue>
    <description>Budget Day</description>
    <inlineHelpText>Budget Day</inlineHelpText>
    <label>Month Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/fields/Remaining_Budget__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Budget__c</fullName>
    <description>Remaining Budget Amount</description>
    <formula>Budgeted_Amount__c - Actual_Spent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Remaining Budget Amount</inlineHelpText>
    <label>Remaining Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/GetYearlyBudget.cls
public class GetYearlyBudget {
    @AuraEnabled(cacheable=true)
    public static List<Monthly_Budget__c> getYearlyBudget() {
        Integer currentYear = Datetime.now().year();
        Date firstJan = Date.newInstance(currentYear, 1, 1);

        return [SELECT Id, Name, Remaining_Budget__c, Month_Year__c 
                FROM Monthly_Budget__c 
                WHERE Month_Year__c >= :firstJan 
                ORDER BY Month_Year__c ASC];
    }
}