force-app/main/default/objects/Monthly_Budget__c/Monthly_Budget__c.object-meta.xml
<CustomObject>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>BUD-{00000}</displayFormat>
        <label>Monthly Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Budget__c/fields/Budgeted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budgeted_Amount__c</fullName>
    <description>Planned spending</description>
    <inlineHelpText>Planned spending</inlineHelpText>
    <label>Budgeted Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()), MONTH(TODAY()), 1)</defaultValue>
    <description>Budget Day</description>
    <inlineHelpText>Budget Day</inlineHelpText>
    <label>Month Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/fields/Remaining_Budget__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Budget__c</fullName>
    <description>Remaining Budget Amount</description>
    <formula>Budgeted_Amount__c - Actual_Spent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Remaining Budget Amount</inlineHelpText>
    <label>Remaining Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BudgetController.cls
public with sharing class BudgetController {

    @AuraEnabled(cacheable=true)
    public static List<Monthly_Budget__c> getYearlyBudgets() {
        Integer currentYear = Date.today().year();
        Date firstJan = Date.newInstance(currentYear, 1, 1);

        return [
            SELECT Id, Name, Month_Year__c, Remaining_Budget__c, Budgeted_Amount__c
            FROM Monthly_Budget__c
            WHERE Month_Year__c >= :firstJan
            ORDER BY Month_Year__c ASC
        ];
    }

    @AuraEnabled
    public static void deleteBudget(Id budgetId) {
        delete [SELECT Id FROM Monthly_Budget__c WHERE Id = :budgetId];
    }
}