force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bills</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Monthly_Budget__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Budget__c</fullName>
    <label>Monthly Budget</label>
    <referenceTo>Monthly_Budget__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/Monthly_Budget__c.object-meta.xml
<CustomObject>
    <label>Monthly Budget</label>
    <nameField>
        <displayFormat>BUD-{00000}</displayFormat>
        <label>Monthly Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Budget__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Same as Expense categories</description>
    <inlineHelpText>Same as Expense categories</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Budget__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()), MONTH(TODAY()), 1)</defaultValue>
    <description>Budget Day</description>
    <inlineHelpText>Budget Day</inlineHelpText>
    <label>Month Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ExpenseController.cls
public with sharing class ExpenseController {
	
	@AuraEnabled(cacheable=true)
    public static Id getMonthlyBudgetId(){
        // Get the current date
		Date todaysDate = Date.today();

		// Get the first day of the current month
		Date firstDayOfMonth = todaysDate.toStartOfMonth();

		return [
           SELECT Id
           FROM Monthly_Budget__c 
           WHERE Month_Year__c=:firstDayOfMonth
        ].Id;
    }
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getCategoryWiseExpenses(Id monthlyBudgetId) {
        return [
            SELECT Category__c category, SUM(Amount__c) total
            FROM Expense__c 
			WHERE Monthly_Budget__c=:monthlyBudgetId
            GROUP BY Category__c 
        ];
    }

	@AuraEnabled(cacheable=true)
    public static List<AggregateResult> getCategoryWiseMonthlyExpenses() {
        Integer currentYear = Datetime.now().year();
        Date firstJan = Date.newInstance(currentYear, 1, 1);
        Date today = Date.today();

        return [SELECT Category__c, Monthly_Budget__r.Month_Year__c, SUM(Amount__c) total
                FROM Expense__c
                WHERE Monthly_Budget__r.Month_Year__c >= :firstJan AND Monthly_Budget__r.Month_Year__c <= :today
                GROUP BY Monthly_Budget__r.Month_Year__c,Category__c
                ORDER BY Monthly_Budget__r.Month_Year__c ASC];
    }
    @AuraEnabled(cacheable=true)
    public static List<Monthly_Budget__c> getMonthlyBudgets() {
        Integer currentYear = Datetime.now().year();
        Date firstJan = Date.newInstance(currentYear, 1, 1);
    
        return [
            SELECT Id, Name, Month_Year__c 
            FROM Monthly_Budget__c 
            WHERE Month_Year__c >= :firstJan
            ORDER BY Month_Year__c ASC
        ];
    }
	
	@AuraEnabled
    public static List<AggregateResult> getCategoryWiseThisMonthExpenses(Id monthlyBudgetId) {
        if (monthlyBudgetId == null) return new List<AggregateResult>();
    
        return [
            SELECT Category__c, Monthly_Budget__r.Month_Year__c, SUM(Amount__c) total
            FROM Expense__c
            WHERE Monthly_Budget__c = :monthlyBudgetId
            GROUP BY Category__c, Monthly_Budget__r.Month_Year__c
            ORDER BY Monthly_Budget__r.Month_Year__c ASC
        ];
    }
	
	@AuraEnabled(cacheable=true)
    public static List<Expense__c> getExpenses() {
        Id monthlyId=getMonthlyBudgetId();
        return [
            SELECT Id, Expense_Date__c, Amount__c, Category__c, Description__c, Monthly_Budget__r.Month_Year__c
            FROM Expense__c 
            WHERE Monthly_Budget__c=:monthlyId
            ORDER BY Expense_Date__c DESC
        ];
    }

    @AuraEnabled
    public static void deleteExpense(Id expenseId) {
        try {
            delete [SELECT Id FROM Expense__c WHERE Id = :expenseId];
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
	
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getMonthlyExpenseTotals() {
        Integer currentYear = Datetime.now().year();
        Date firstJan = Date.newInstance(currentYear, 1, 1);
        Date today = Date.today();
    
        return [
            SELECT CALENDAR_MONTH(Expense_Date__c) month, SUM(Amount__c) total
            FROM Expense__c
            WHERE Expense_Date__c >= :firstJan AND Expense_Date__c <= :today
            GROUP BY CALENDAR_MONTH(Expense_Date__c)
            ORDER BY CALENDAR_MONTH(Expense_Date__c)
        ];
    }

}